version: "3"

services:

  config:
    build:
      dockerfile: Dockerfile
      context: ./config
    image: test/config-server
    container_name: config
    ports:
      - "8081:8080"
    networks:
      - "local-tests"

  discovery:
    build:
      dockerfile: Dockerfile
      context: ./discovery
    image: test/registry-server
    container_name: discovery
    ports:
      - "8082:8080"
    networks:
      - "local-tests"

  svc-book-1:
    build:
      dockerfile: Dockerfile
      context: ./svc-book
    image: test/svc-book
    container_name: svc-book-1
    ports:
      - "8083:8080"
    networks:
      - "local-tests"
    depends_on:
      - "config"
      - "discovery"

  svc-book-2:
    build:
      dockerfile: Dockerfile
      context: ./svc-book
    image: test/svc-book
    container_name: svc-book-2
    ports:
      - "8084:8080"
    networks:
      - "local-tests"
    depends_on:
      - "config"
      - "discovery"

  clients-1:
    build:
      dockerfile: Dockerfile
      context: ./clients/
    image: test/book-clients-api
    container_name: clients-1
    ports:
      - "9000:8080"
    networks:
      - "local-tests"
    depends_on:
      - "config"
      - "discovery"
      - "svc-book-1"
      - "svc-book-2"

#  clients-2:
#    build:
#      dockerfile: Dockerfile
#      context: ./clients/
#    image: test/book-clients-api
#    container_name: clients-2
#    ports:
#      - "9001:8080"
#    networks:
#      - "local-tests"
#    depends_on:
#      - "config"
#      - "discovery"
#      - "svc-book-1"
#      - "svc-book-2"

networks:
  local-tests:
    driver: bridge  

