version: "3"

services:

  config:
    build:
      dockerfile: Dockerfile
      context: ./config
    image: test/config-server
    container_name: config
    ports:
      - "8081"
    networks:
      - "local-tests"

  discovery:
    build:
      dockerfile: Dockerfile
      context: ./discovery/
    image: test/registry-server
    container_name: discovery
    ports:
      - "8082"
    networks:
      - "local-tests":
      dockerfile: Dockerfile
      context: ./svc-book/
    image: test/book-api
    container_name: book2
    ports:
      - "8083"
    networks:
      - "local-tests"
    depends_on:
      - "config"
      - "discovery"

  clients:
    build:
      dockerfile: Dockerfile
      context: ./clients/
    image: test/book-clients-api
    container_name: clients
    ports:
      - "9000"
    networks:
      - "local-tests"
    depends_on:
      - "config"
      - "discovery"
      - "book1"
      - "book2"

networks:
  local-tests:
    driver: bridge  

